name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.1
  cloud_firestore: ^0.12.6
  firebase_auth: ^0.11.1+7
  firebase_core: ^0.4.0+6
  font_awesome_flutter: ^8.4.0
  flutter_spinkit: ^3.1.0
  provider: ^3.0.0+1
  modal_progress_hud: ^0.1.3
  unicorndial: ^1.1.5
  flutter_datetime_picker: ^1.2.5
  get_it: ^1.0.3+2
  firebase_storage: ^3.0.4





dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Thin.ttf
        - asset: fonts/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato-ThinItalic.ttf
          style: italic


  uses-material-design: true

  assets:
  - images/
